  regexs:
  - "AIza[0-9A-Za-z\\-_]{35}"
  - 'bearer [a-zA-Z0-9_\\-\\.=]+'
  - 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)'
  - '(eyJ|YTo|Tzo|PD[89]|aHR0cHM6L|aHR0cDo|rO0)[a-zA-Z0-9+/]+={0,2}'
  - "(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\\/+]{40}['\"]"
  - "(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}"
  - "firebase.initializeApp(.*\\s*[\\w*\\s*a-zA-Z]*\\w.*){100}"
  - "//s3\\.amazonaws\\.com/[a-z0-9._-]+"
  - "//s3-[a-z0-9-]+\\.amazonaws\\.com/[a-z0-9._-]+"